### ISSUE TITLE
jupyter notebook solution

### ISSUE THREAD

**Issue by hillcharlotte** [ribernhard/PS239T#1]
I was having an issue with this line of code in terminal:

$ jupyter notebook

Instead of launching the notebook, it gave me a URL to paste into my browser.

The solution is to use this line of code instead:

$jupyter notebook --browser=Chrome

Hope that's helpful!

**Comment by ribernhard** [comment]
Thanks! This code will work for some people but not others. As a result, I'm not adding to the main installation file, but go ahead and copy your code into bCourses as well in case anyone else has the same issue.
