### ISSUE TITLE
Git Bash

### ISSUE THREAD

**Issue by rojasernesto** [ribernhard/PS239T#2]
Hey All,

Not sure if anyone else is running into this issue but when I search for whether I have installed Python and R GitBash says

bash: R: command not found

However, the issue is that I do have R and am confused as to why I am having this error.

**Comment by ribernhard** [comment]
Ernesto, this is probably a path problem. Did the code on the whiteboard today resolve this?

**Comment by davidnield** [comment]
Tried the code on the board. Wasn't sure if there was supposed to be a space before >.bashrc and wasn't sure which folder to use (the R folder which just has the R version folder, or the R version folder itself). I iterated through all four possibilities and getting the same error.

Screenshot in case it helps: https://i.imgur.com/R1suKVN.png

**Comment by davidnield** [comment]
I think I figured it out! You need to navigate to the specific R subfolder that contains the R.exe file. The default is R\R-[version #]\bin

Here's a screenshot if it helps: https://i.imgur.com/wDUDrs5.png

**Comment by davidnield** [comment]
And the code:

export PATH="PATH:C:\Program Files\R\R-3.4.1\bin"

echo 'export PATH="$PATH:C:\Program Files\R\R-3.4.1\bin"' >.bashrc

**Comment by ribernhard** [comment]
10 points to Gryffindor, David! Recommend re-posting to bCourses as well so you get credit for the solution.

**Comment by davidnield** [comment]
Note that in the working screenshot you drop the $ for the first line of code, this ended up being the difference in getting someone else's working for some reason.
